GET http://localhost:3000/users HTTP/1.1

################################################
POST http://localhost:3000/users
Content-Type: application/json

{
  "nombreUsuario": "BrandonSGC",
  "nombre": "Brandon",
  "apellidos": "Gomez Carvajal",
  "email": "bransti20@gmail.com",
  "contrasena": "bran123",
  "rolID": 1
}

################################################
POST http://localhost:3000/users
Content-Type: application/json

{
  "nombreUsuario": "CarlitosGB",
  "nombre": "Carlos",
  "apellidos": "Gomez Badilla",
  "email": "carlitos@gmail.com",
  "contrasena": "car123",
  "rolID": 1
}


################################################
PUT http://localhost:3000/users/CarlitosGB
Content-Type: application/json

{
  "nombre": "Carlossss",
  "apellidos": "Gomez Badilla",
  "email": "carlitos@gmail.com",
  "contrasena": "car123",
  "rolID": 1
}

################################################
DELETE http://localhost:3000/users/BrandonSGC
Content-Type: application/json

